### PR TITLE
XS-APItest

### PR DESCRIPTION
**Pull request by atoomic**
This is fixing a few tests from #82

### CODE REVIEW

**Comment by jkeenan** [comment]
When I create a dummy branch from `p7` and then apply the patch from this p.r. to that branch, and then run `make test` on the `ext/XS-APItest/` directory, I get warnings or failures in these files:
```
t/../ext/XS-APItest/t/newCONSTSUB ............... Prototype mismatch: sub main::ZZIP () vs none at t/newCONSTSUB.t line 101.
Prototype mismatch: sub main::BRRRAPP () vs none at t/newCONSTSUB.t line 101.
ok

t/../ext/XS-APItest/t/svpv_magic ................ #   Failed test 'SvPVutf8 calls get-magic once'
#   at t/svpv_magic.t line 59.
#          got: undef
#     expected: '1'
#   Failed test 'SvPVutf8 does not stop stringification from calling FETCH'
#   at t/svpv_magic.t line 61.
#          got: undef
#     expected: '2'
# Looks like you failed 2 tests of 10.
FAILED at test 9

t/../ext/XS-APItest/t/xs_special_subs_require ... #   Failed test 'There were 2 warnings'
#   at t/xs_special_subs_require.t line 89.
#          got: '0'
#     expected: '2'
#   Failed test at t/xs_special_subs_require.t line 90.
#                   undef
#     doesn't match '(?^:^Too late to run CHECK block)'
#   Failed test at t/xs_special_subs_require.t line 91.
#                   undef
#     doesn't match '(?^:^Too late to run INIT block)'
# Looks like you failed 3 tests of 104.
FAILED at test 72
```
The failures in `ext/XS-APItest/t/svpv_magic.t` and `ext/XS-APItest/t/xs_special_subs_require.t` were reported in https://github.com/atoomic/perl/issues/82.  So I'm not surprised at seeing them here.

But the warnings emitted by `ext/XS-APItest/t/newCONSTSUB.t` were not seen in https://github.com/atoomic/perl/issues/82.
```
Prototype mismatch: sub main::ZZIP () vs none at t/newCONSTSUB.t line 101.
Prototype mismatch: sub main::BRRRAPP () vs none at t/newCONSTSUB.t line 101.
```
Can you investigate that further?

Thanks.
jimk

**Comment by jkeenan** [comment]
> When I create a dummy branch from `p7` and then apply the patch from this p.r. to that branch, and then run `make test` on the `ext/XS-APItest/` directory, I get warnings or failures in these files:
> 
> ```
> t/../ext/XS-APItest/t/newCONSTSUB ............... Prototype mismatch: sub main::ZZIP () vs none at t/newCONSTSUB.t line 101.
> Prototype mismatch: sub main::BRRRAPP () vs none at t/newCONSTSUB.t line 101.
> ok
> 

[snip]

> 
> But the warnings emitted by `ext/XS-APItest/t/newCONSTSUB.t` were not seen in #82.
> 
> ```
> Prototype mismatch: sub main::ZZIP () vs none at t/newCONSTSUB.t line 101.
> Prototype mismatch: sub main::BRRRAPP () vs none at t/newCONSTSUB.t line 101.
> ```

That, of course, could simply have been that I overlooked them.  So what I did was to build a regular Perl at blead and run this test.  The two `Prototype mismatch` warnings are not being emitted in blead.  (And in blead this test is running with `use warnings;` in the relevant section of the file.)

So this appears to be a regression from blead.

> 
> Can you investigate that further?
> 
> Thanks.
> jimk

**Comment by atoomic** [comment]
going to check

**Comment by atoomic** [comment]
69440720 is fixing the issue from `ext/XS-APItest/t/newCONSTSUB.t`
The failures in `ext/XS-APItest/t/svpv_magic.t` and `ext/XS-APItest/t/xs_special_subs_require.t` still have to be fixed, and this would be done by a different PR.

**Comment by jkeenan** [comment]
> [6944072](https://github.com/atoomic/perl/commit/694407201514d60983ab83d8a945032da9632d1c) is fixing the issue from `ext/XS-APItest/t/newCONSTSUB.t`

Confirmed.  Please apply to p7 when you get a chance.

> The failures in `ext/XS-APItest/t/svpv_magic.t` and `ext/XS-APItest/t/xs_special_subs_require.t` still have to be fixed, and this would be done by a different PR.

Okay.

**Pull request merged**
