### PR TITLE
make perl5db.pl back

### PR DESCRIPTION
**Pull request by eiro**

### CODE REVIEW

**Comment by atoomic** [comment]
keeping this open for now

**Comment by eiro** [comment]
what if i try to make it work? i mean: it seems to be a good simple contribution and i definitely want to help on perl7

**Comment by atoomic** [comment]
I think a better plan would be to rename `perl5db` to `perldb` so this would avoid to bump the version over time and major releases.

**Comment by eiro** [comment]
> I think a better plan would be to rename `perl5db` to `perldb` so this would avoid to bump the version over time and major releases.

totally agree

**Comment by briandfoy** [comment]
Or, even call it `perldebug` so people don't think it's a database thing :)

**Comment by atoomic** [comment]
`perldebug` is definitively a better name! I think this work should be done and submitted as a PR to blead.

**Comment by atoomic** [comment]
I'm going to close this PR as it's currently conflicting and using something like `perldebug` instead of `perl5db` is a better choice. Ideally this should be submitted to `blead`

#105 is going to track the progress on this idea.

Feel free to reopen/resubmit with a better patch

thanks for your understanding

**Pull request closed without merging**
