### PR TITLE
Fixes for ext/POSIX

### PR DESCRIPTION
**Pull request by atoomic**
Fixes issues from #76

### CODE REVIEW

**Comment by jkeenan** [comment]
Applying your patch to a dummy branch forked from `p7`, I get this:
```
t/../ext/POSIX/t/posix ............ Useless use of a constant ("NUMERIC") in void context at t/posix.t line 365.
Use of uninitialized value in subroutine entry at t/posix.t line 361.
ok
t/../ext/POSIX/t/sigaction ........ ok
t/../ext/POSIX/t/sigset ........... ok
t/../ext/POSIX/t/strerror_errno ... ok
t/../ext/POSIX/t/sysconf .......... close() on unopened filehandle 3 at t/sysconf.t line 126.
ok
```
Can you investigate?

Thanks.
jimk

**Comment by jkeenan** [comment]
> Applying your patch to a dummy branch forked from `p7`, I get this:
> 
> ```
> t/../ext/POSIX/t/posix ............ Useless use of a constant ("NUMERIC") in void context at t/posix.t line 365.
> Use of uninitialized value in subroutine entry at t/posix.t line 361.
> ok
> t/../ext/POSIX/t/sigaction ........ ok
> t/../ext/POSIX/t/sigset ........... ok
> t/../ext/POSIX/t/strerror_errno ... ok
> t/../ext/POSIX/t/sysconf .......... close() on unopened filehandle 3 at t/sysconf.t line 126.
> ok
> ```
> 
> Can you investigate?
> 
> Thanks.
> jimk

The warnings in `ext/POSIX/t/*.t` could be alleviated with:
```
$ git diff |cat
diff --git a/ext/POSIX/t/posix.t b/ext/POSIX/t/posix.t
index 46fe641113..dac3680d2b 100644
--- a/ext/POSIX/t/posix.t
+++ b/ext/POSIX/t/posix.t
@@ -15,7 +15,6 @@ use Test::More tests => 96;
 
 use POSIX qw(fcntl_h signal_h limits_h _exit getcwd open read strftime write
 	     errno localeconv dup dup2 lseek access);
-use strict 'subs';
 
 sub next_test {
     my $builder = Test::More->builder;
@@ -358,11 +357,14 @@ is ($result, undef, "fgets should fail");
 like ($@, qr/^Unimplemented: POSIX::fgets\(\): Use method IO::Handle::gets\(\) instead/,
       "check its redef message");
 
-eval { use strict; POSIX->import("S_ISBLK"); my $x = S_ISBLK };
+eval { POSIX->import("S_ISBLK"); no warnings 'uninitialized'; my $x = S_ISBLK };
 unlike( $@, qr/Can't use string .* as a symbol ref/, "Can import autoloaded constants" );
 
 SKIP: {
-    skip("locales not available", 26) unless locales_enabled(qw(NUMERIC MONETARY));
+    {
+        no warnings 'void';
+        skip("locales not available", 26) unless locales_enabled(qw(NUMERIC MONETARY));
+    }
     skip("localeconv() not available", 26) unless $Config{d_locconv};
     my $conv = localeconv;
     is(ref $conv, 'HASH', 'localeconv returns a hash reference');
```

**Comment by jkeenan** [comment]
The warnings in `ext/POSIX/t/sysconf.t` could be treated with:
```
$ git diff -- ext/POSIX/t/sysconf.t
diff --git a/ext/POSIX/t/sysconf.t b/ext/POSIX/t/sysconf.t
index 29cf20f210..d25e86a644 100644
--- a/ext/POSIX/t/sysconf.t
+++ b/ext/POSIX/t/sysconf.t
@@ -6,7 +6,6 @@ BEGIN {
     plan skip_all => "POSIX is unavailable" if $Config{'extensions'} !~ m!\bPOSIX\b!;
 }
 
-use strict;
 use File::Spec;
 use POSIX;
 
@@ -123,7 +122,10 @@ SKIP: {
                          "calling fpathconf($fd, $constant) ($TTY)");
     }
     
-    close($fd);
+    {
+        no warnings 'unopened';
+        close($fd);
+    }
     # testing pathconf() on a terminal file
     for my $constant (@path_consts_terminal) {
        _check_and_report(sub { pathconf($TTY, shift) }, $constant,
```

**Comment by jkeenan** [comment]
@atoomic, since I was able to diagnose the remaining problems in two files, I went ahead and corrected them, pushed to `upstream/POSIX` and proceeded with the merge.

**Comment by atoomic** [comment]
thanks @jkeenan

**Pull request merged**
